let provincias

provincias.push("Álava")
provincias.push("Albacete")
provincias.push("Alicante")
provincias.push("Almería")
provincias.push("Ávila")
provincias.push("Badajoz")
provincias.push("Baleares (Islas)")
provincias.push("Barcelona")
provincias.push("Burgos")
provincias.push("Cáceres")
provincias.push("Cádiz")
provincias.push("Castellón")
provincias.push("Ciudad Real")
provincias.push("Córdoba")
provincias.push("Coruña (La)")
provincias.push("Cuenca")
provincias.push("Girona")
provincias.push("Granada")
provincias.push("Guadalajara")
provincias.push("Guipúzcoa")
provincias.push("Huelva")
provincias.push("Huesca")
provincias.push("Jaén")
provincias.push("León")
provincias.push("Lleida")
provincias.push("Rioja (La)")
provincias.push("Lugo")
provincias.push("Madrid")
provincias.push("Málaga")
provincias.push("Murcia")
provincias.push("Navarra")
provincias.push("Ourense")
provincias.push("Asturias")
provincias.push("Palencia")
provincias.push("Palmas (Las)")
provincias.push("Pontevedra")
provincias.push("Salamanca")
provincias.push("Santa Cruz de Tenerife")
provincias.push("Cantabria")
provincias.push("Segovia")
provincias.push("Sevilla")
provincias.push("Soria")
provincias.push("Tarragona")
provincias.push("Teruel")
provincias.push("Toledo")
provincias.push("Valencia")
provincias.push("Valladolid")
provincias.push("Vizcaya")
provincias.push("Zamora")
provincias.push("Zaragoza")
provincias.push("Ceuta")
provincias.push("Melilla")
